# Generated by Django 5.1.3 on 2024-12-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('University_Year', models.IntegerField()),
                ('Sleep_Duration', models.FloatField()),
                ('Study_Hours', models.FloatField()),
                ('Screen_Time', models.FloatField()),
                ('Caffeine_Intake', models.FloatField()),
                ('Physical_Activity', models.FloatField()),
                ('Sleep_Quality', models.FloatField(blank=True, null=True)),
                ('Weekday_Sleep_Start', models.TimeField()),
                ('Weekday_Sleep_End', models.TimeField()),
                ('Weekend_Sleep_Start', models.TimeField()),
                ('Weekend_Sleep_End', models.TimeField()),
            ],
        ),
    ]
